apiVersion: v1
kind: Pod
metadata:
  name: unix-socket-pod
spec:
  containers:
    - name: server
      imagePullPolicy: Never
      image: docker.io/library/unix-socket-pod:latest 
      command: ["/bin/sh", "-c", "/usr/local/bin/server"]
      volumeMounts:
        - mountPath: /var/some_socket
          name: socket-volume
    - name: client
      imagePullPolicy: Never
      image: docker.io/library/unix-socket-pod:latest 
      command: ["/bin/sh", "-c", "/usr/local/bin/client"]
      volumeMounts:
        - mountPath: /var/some_socket
          name: socket-volume
  volumes:
    - name: socket-volume
      emptyDir: {}

