---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-a-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-a-binding
subjects:
  - kind: ServiceAccount
    name: user-a
    namespace: default
roleRef:
  kind: ClusterRole
  name: user-a-clusterrole
  apiGroup: rbac.authorization.k8s.io