#!/bin/bash

set -euo pipefail
#TODO: some parametrization needed for deps updates
: "${ARTIFACTS_SERVER:=http://dsdsc.cse.com}"
: "${ARTIFACTS_PATH:=p4}"
: "${DEPS_DIR:=./deps-dir}"

function download(){
  declare downloads=(
      HLSProSetup-19.2.0.57-linux.run
      bsp-fw.sh.new.tar.gz
      p4.release-14.v0.8.0.tar.gz
      p4.release.v0.0.0.199a2e4c.tar.gz
      n3000_ias_1_3_1_pv_dev_centos_installer.tar.gz
      boost_1_71_0.tar.gz
      )

  mkdir $DEPS_DIR

  for path in "${downloads[@]}"
  do
    echo "INFO: Downloading $ARTIFACTS_SERVER/$ARTIFACTS_PATH/$path"
    wget -q -P deps-dir $ARTIFACTS_SERVER/$ARTIFACTS_PATH/$path
    if [[ $path == *"tar.gz" ]] || [[ $path == *"tgz" ]]; then
      echo "INFO: Extracting $DEPS_DIR/$path"
      tar -xz -C $DEPS_DIR -f $DEPS_DIR/$path && rm -f $DEPS_DIR/$path
    fi
  done
}

function run_devstack_install(){
  chmod +x $DEPS_DIR/n3000_ias_1_3_1_pv_dev_centos_installer/n3000-1.3.8-4-dev-el7-setup.sh
  expect /devstack.exp $DEPS_DIR/n3000_ias_1_3_1_pv_dev_centos_installer/n3000-1.3.8-4-dev-el7-setup.sh
  echo 'HLS_BIN="/root/inteldevstack/intelFPGA_pro/hls/bin/"
if [[ ":${PATH}:" = *":${HLS_BIN}:"* ]] ;then/harbor.smartnic.codilime.com/
        echo "$HLS_BIN is in PATH already"
else
        echo "Adding $HLS_BIN to PATH"
        export PATH="${HLS_BIN}":"${PATH}"
fi'  >> ~/inteldevstack/bin/init_env.sh
}

function run_synthesis_install(){
  chmod +x $DEPS_DIR/HLSProSetup-19.2.0.57-linux.run
  expect /synthesis.exp $DEPS_DIR/HLSProSetup-19.2.0.57-linux.run
}

function copy_p4c_bsp_to_bin(){
  chmod +x $DEPS_DIR/bsp-fw.sh.new/bsp-fw.sh
  cp $DEPS_DIR/bsp-fw.sh.new/bsp-fw.sh /usr/bin
  chmod +x $DEPS_DIR/p4.release-14.v0.8.0/compiler/p4vhdl/p4-vhdl
  cp $DEPS_DIR/p4.release-14.v0.8.0/compiler/p4vhdl/p4-vhdl /usr/bin
  chmod +x $DEPS_DIR/p4.release.v0.0.0.199a2e4c/p4c-p4vhdl-centos7
  cp $DEPS_DIR/p4.release.v0.0.0.199a2e4c/p4c-p4vhdl-centos7 /usr/bin/p4c-p4vhdl
}

function run_boost_install(){
  pushd $DEPS_DIR/boost_1_71_0
  ./bootstrap.sh
  ./b2
  popd
}

function install(){
  run_devstack_install
  run_synthesis_install
  copy_p4c_bsp_to_bin
  run_boost_install
}

function all(){
  download
  install
}

function cleanup(){
  rm -rf $DEPS_DIR
  yum clean all
  rm -rf /var/cache/yum || true
}

while [ $# -gt 0 ]; do
  case "$1" in
    download) download; exit;;
    run_devstack_install) run_devstack_install; exit;;
    run_synthesis_install) run_synthesis_install; exit;;
    copy_p4c_bsp_to_bin) copy_p4c_bsp_to_bin; exit;;
    run_boost_install) run_boost_install; exit;;
    all) all; exit;;
    download) download; exit;;
    install) install; exit;;
    cleanup) cleanup; exit;;
  esac
  shift
done